### ISSUE TITLE
Images load extremely slowly; exceptionally high RAM use

### ISSUE THREAD

**Issue by 526christian** [toshiaki1729/dataset-tag-editor-standalone#21]
For context, I did a gradio update to fix the issue from issue #20. Both 3.37 and 3.36.1 are the same for this problem. Deprecation warnings for style and grid parameters appear in the command window.

Loading a ~100MB dataset of 43 images (stored on a 2TB MX300 SSD) is taking almost 7 minutes, with RAM consumption topping out at 3.6 GB in the Python process once the images become viewable in the UI. This occurs in both Firefox and Chrome. I'm on Windows 10, and didn't have this problem in Linux a couple weeks ago (prior to the Pydantic V2 release). My Linux OS install is broken, so I can't test if this is specific to my Windows install, or is prompted by the gradio update.

**Comment by CostaConcord** [comment]
Same issue, makes the thing basically unusable. Perhaps the issue is related to this message on startup, pasted below. 


/Users/dataset-tag-editor-standalone/scripts/tab_main.py:325: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
/Users/dataset-tag-editor-standalone/scripts/ui/block_dataset_gallery.py:32: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  self.gl_dataset_images = gr.Gallery(
/Users/dataset-tag-editor-standalone/scripts/ui/block_dataset_gallery.py:32: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'grid_cols' in the constructor instead.
  self.gl_dataset_images = gr.Gallery(
/Users/dataset-tag-editor-standalone/scripts/ui/tab_filter_by_selection.py:42: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  self.gl_filter_images = gr.Gallery(
/Users/trotsky/ml-stable-diffusion/dataset-tag-editor-standalone/scripts/ui/tab_filter_by_selection.py:42: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'grid_cols' in the constructor instead.
  self.gl_filter_images = gr.Gallery(

**Comment by aDropp** [comment]
I had same issue. I searched on the Internet and found a same issue and solution ([link](https://github.com/subzeroid/instagrapi/issues/1435)). When I tried to return `gradio==3.22.1` and downgrade the `pydantic==1.10.9`, it worked fine.

**Comment by toshiaki1729** [comment]
I've updated gradio to 4.28.3 in >= ver0.0.6.
Version related issue may be solved.
I'm grad if you can check it.
